/** Espelha `GrauParentesco` (abrigo-backend, app/features/composicao_familiar/
 * models.py) — lista fechada, antes era texto livre (ver migração 0023). */
export const GRAUS_PARENTESCO = [
  'Pai',
  'Mãe',
  'Filho',
  'Filha',
  'Esposo',
  'Esposa',
  'Companheiro',
  'Companheira',
  'Namorado',
  'Namorada',
  'Irmão',
  'Irmã',
  'Avô',
  'Avó',
  'Bisavô',
  'Bisavó',
  'Neto',
  'Neta',
  'Bisneto',
  'Bisneta',
  'Genro',
  'Nora',
  'Sogro',
  'Sogra',
  'Cunhado',
  'Cunhada',
  'Tio',
  'Tia',
  'Sobrinho',
  'Sobrinha',
  'Primo',
  'Prima',
  'Enteado',
  'Enteada',
  'Padrasto',
  'Madrasta',
  'Cuidador',
  'Cuidadora',
  'Responsável',
  'Outro'
] as const;

export type GrauParentesco = (typeof GRAUS_PARENTESCO)[number];
